### ISSUE TITLE
[Feature Request]: Support for new OpenAI model: `gpt-3.5-turbo-16k`

### ISSUE THREAD

**Issue by rishabh-bhargava** [refuel-ai/autolabel#309]
**Is your feature request related to a problem? Please describe.**
We want to support the latest models in Autolabel, and OpenAI just launched: `gpt-3.5-turbo-16k`. 

**Describe the solution you'd like**
A user should be able to specify and use this new model in their configurations going forward.

**Comment by rishabh-bhargava** [comment]
Also might want to add support for `gpt-3.5-turbo-0613`. cc: @DhruvaBansal00

**Comment by nihit** [comment]
https://github.com/refuel-ai/autolabel/pull/339
