### ISSUE TITLE
[Bug]: `get_data` shows the number of bytes being downloaded, but not the unit (bytes)

### ISSUE THREAD

**Issue by rishabh-bhargava** [refuel-ai/autolabel#324]
**Describe the bug**
Today, running `get_data` prints out the number of bytes being downloaded, but we should explicitly say it's bytes being downloaded and not kilobytes or number of rows. 

**To Reproduce**
```
from autolabel import get_data

get_data('civil_comments')
```

**Expected behavior**
we should say "bytes" somewhere. 

**Screenshots**
<img width="791" alt="image" src="https://github.com/refuel-ai/autolabel/assets/1568137/77f0fdbf-5a99-4f79-afb9-75201914de54">

**Comment by JTarakRam** [comment]
I have solved this, where can explicitly say the bytes of download, and created PR for the same :)
