### ISSUE TITLE
[Feature Request]: Support logit_bias to constrain LLM outputs 

### ISSUE THREAD

**Issue by nihit** [refuel-ai/autolabel#352]
**Is your feature request related to a problem? Please describe.**
LLM might sometimes have trouble following output format instructions

**Describe the solution you'd like**
logit_bias: https://twitter.com/AAAzzam/status/1669753725093654565

**Comment by nihit** [comment]
We can start with support for classification and entity matching tasks

**Comment by nihit** [comment]
thanks @neildhruva for the suggestion!

**Comment by DhruvaBansal00** [comment]
logit_bias is an OpenAI only  feature at the moment.
For huggingface equivalent, we can use this: https://huggingface.co/docs/transformers/main/en/internal/generation_utils#transformers.SequenceBiasLogitsProcessor
