### ISSUE TITLE
Support for data labeling with custom LLMs

### ISSUE THREAD

**Issue by nihit** [refuel-ai/autolabel#390]
A custom LLM allows a user to plug-in their LLM into the Autolabel library for the task of data labeling. This could be hosted on their local machine or in a cloud that can called with an API. 

High level design: 

1. A new "Custom LLM" class that extends the Autolabel BaseModel (https://github.com/refuel-ai/autolabel/blob/main/src/autolabel/models/base.py). This class needs to override two methods: `label` and `get_cost` in addition to any initialization logic.

2. For reference, take a look at other LLM provider classes:
-- OpenAI, Cohere, Anthropic etc internally call Langchain's LLM class (e.g. https://github.com/refuel-ai/autolabel/blob/main/src/autolabel/models/cohere.py#L37)
-- HuggingFace initializes a huggingface pipeline (e.g. https://github.com/refuel-ai/autolabel/blob/main/src/autolabel/models/hf_pipeline.py#L76)

3. For the custom LLM, we'd want the user to pass in a callable function with the following signature. This can be one of the parameters passed in the config Dictionary in the init call.
```
def callable_fn(prompt: str) -> str:
      <custom LLM logic here>
      return <completion response from LLM>
```

4. The Custom LLM class calls this function for labeling. 

5. To use the custom LLM class, add the relevant if/else case here: https://github.com/refuel-ai/autolabel/blob/main/src/autolabel/models/__init__.py#L11 
the provider can be "custom" or "self-hosted"

**Comment by nihit** [comment]
@Sardhendu to work on this

**Comment by nihit** [comment]
@rajasbansal for comments or suggested changes

**Comment by rajasbansal** [comment]
lgtm - we should allow loading on both cpu and gpu
