### ISSUE TITLE
[Bug]: Consolidate calculate f1

### ISSUE THREAD

**Issue by Tyrest** [refuel-ai/autolabel#409]
**Describe the bug**
Currently, we compute f1 in two different places: `tasks/utils.py` and in `multilabel_classification.py` with `sklearn`. We should consolidate these functions into a single place and use that instead.

**Additional context**
See conversation about this [here](https://github.com/refuel-ai/autolabel/pull/405#pullrequestreview-1504612482)

**Comment by nihit** [comment]
@rajasbansal to review
