### ISSUE TITLE
[Feature Request]: Validate the fields in `example_template` during `agent.plan`

### ISSUE THREAD

**Issue by rishabh-bhargava** [refuel-ai/autolabel#422]
**Is your feature request related to a problem? Please describe.**
When a user provides an `example_template` to be used as their LLM prompt, they can provide column names from their CSV to be templated in at runtime. However, when running `agent.plan` or `agent.run`, we find that the command doesn't throw an error. Instead it fails silently. For example if we change the config [here](https://github.com/refuel-ai/autolabel/blob/main/examples/banking/config_banking.json) and replace `example_template` value with `"Input: {example1}\nOutput: {label}"`, we see the following:
<img width="1512" alt="image" src="https://github.com/refuel-ai/autolabel/assets/1568137/a33ec272-6af3-46e6-bc89-cfddd41e788e">

**Describe the solution you'd like**
Instead, `agent.plan` and `agent.run` should throw an error when we find columns in the `example_template` that don't exist in the test or seed datasets provided.

**Comment by chirag-manwani** [comment]
@rishabh-bhargava Checking for the column names would work fine in the case of CSV files, but if the templated examples are provided in JSON format(either [like this](https://github.com/refuel-ai/autolabel/blob/43d32676bc37214d7f90cad2ec7cf6b40524b85d/tests/assets/walmart_amazon/config_walmart_amazon.json#L19) or [in a JSON file](https://github.com/refuel-ai/autolabel/blob/main/tests/assets/banking/test.jsonl)), then the only option would be to go through all the examples and check if template variables in the example EXACTLY match with the template variables in the example_template. 

What should be done if only some of the examples in the JSON file have a missing variable? 
What if there is one extra template variable(wrt to the example_template) in the example?

**Comment by rajasbansal** [comment]
A dataset might have some extraneous columns (for eg serial id, hash etc) which might be important for the user in some other context (like deduplication) but not important while creating the prompt. Having additional template variables in the example should probably be ignored in that case.

We can assume that the dataset provided by the user follows the specification of being uniform in the columns present in every example. In case we relax that assumption, we might need to go through all examples. I feel this should be an okay assumption to have.

Thoughts @chirag-manwani @rishabh-bhargava?

**Comment by chirag-manwani** [comment]
I agree that extra columns should be ignored. For the rest I think we should follow this approach- For each example check if columns required are present in the current example, if yes then add it to the dataset, if not then log a warning message, ignore the example and move along. If the final dataset does not have any data points, then we could throw an error. The same error could be thrown in case required columns are missing from the csv file. 

Does this seem like a good approach?

**Comment by nihit** [comment]
@rajasbansal @rishabh-bhargava @chirag-manwani  the recently added validation (https://github.com/refuel-ai/autolabel/blob/main/src/autolabel/data_loaders/validation.py#L274) should handle this ?
