### ISSUE TITLE
[Feature Request]: few_shot_label_diversity flag

### ISSUE THREAD

**Issue by turian** [refuel-ai/autolabel#424]
**Is your feature request related to a problem? Please describe.**

I want to make sure that all possible labels are included as examples in the few-shot examples.

This is particularly important when the labels are imbalanced in the seed set, and thus the common labels are more likely to be retrieved regardless of semantic similarity or MMR.

**Describe the solution you'd like**

few_shot_label_diversity should be a boolean flag. If True, presenting diverse labels should be the primary criterion for selecting the few-shot examples, followed by semantic similarity or max_marginal_relevance.

**Additional context**
It's probably best to demonstrate all possible labels in a balanced way, regardless of whether the labels are very imbalanced. (However, that could be a future TODO.)

There should be some order to the labels and examples are selected in a round-robin fashion, maximizing semantic similarity or MMR.

I *don't* think the round-robin order of labels should go from most frequent to least frequent label, or vice-versa, because that means there will always be the same number of each label shown, which might be biased if few_shot_num // len(labels) != 0.

Instead, my preference would be that the label order is RANDOM. One way to do this but still have cache hits is a deterministic random strategy. i.e. based upon the example batch or the prompt WITHOUT the seed examples in it, use that text to seed a new Python rng. (Python rngs can take an kind of input.) Then, pick the order of the labels in round-robin fashion. This ensures that the order of the few show examples for the prompt are identical for the same batch of examples.

**Comment by nihit** [comment]
Thanks @turian for opening this issue! Absolutely agree with the suggestion to select few-shot examples to ensure label coverage - this will be especially helpful in labeling tasks with a finite label space (classification, entity match, multiple choice question answering, grading generated outputs by assigning it a score on a scale of 1 to 5 etc).

We can support this with two new selection techniques:
1. label diversity -- few-shot examples are selected to ensure coverage across all labels. Within each label, the specific few-shot examples are sampled at random

2. label diversity with semantic similarity -  few-shot examples are selected to ensure coverage across all labels. Within each label, the specific few-shot examples are semantically similar to the input to be labeled. 

Would love to hear your thoughts on this! We're prioritizing this feature in our upcoming sprint - expect some updates on it in the coming week

**Comment by nihit** [comment]
@Abhinav-Naikawadi follow up about implementations for these

**Comment by Abhinav-Naikawadi** [comment]
https://github.com/refuel-ai/autolabel/pull/436

**Comment by turian** [comment]
> 1. label diversity -- few-shot examples are selected to ensure coverage across all labels. Within each label, the specific few-shot examples are sampled at random
> 2. label diversity with semantic similarity -  few-shot examples are selected to ensure coverage across all labels. Within each label, the specific few-shot examples are semantically similar to the input to be labeled.

Yes! This would be everything I need.

**Comment by turian** [comment]
@Abhinav-Naikawadi Could there be a small doc for this?

**Comment by nihit** [comment]
hi @turian  -- we just updated the docs here: https://docs.refuel.ai/guide/accuracy/few-shot/ 

For the new techniques, you can use the following: 
```
"few_shot_selection": "label_diversity_random",
```

and 
```
"few_shot_selection": "label_diversity_similarity",
```

**Comment by nihit** [comment]
this feature will be part of 0.0.8, expecting to release by end of today!

**Comment by nihit** [comment]
https://pypi.org/project/refuel-autolabel/0.0.8/
