### ISSUE TITLE
[Feature Request]: Chain of thought for Classification and Entity Matching tasks?

### ISSUE THREAD

**Issue by turian** [refuel-ai/autolabel#425]
**Is your feature request related to a problem? Please describe.**

It would be great to be able to use chain-of-thought for Classification and Entity Matching tasks.

Reading the LLM explanations allows you to construct better prompts, because you understand what might have been underspecified.

However, the docs suggest that chain of thought is only for QA tasks.

**Describe the solution you'd like**

* Chain of thought being applicable in all tasks
* Documentation update indicating that
* An example of chain of thought for Classification, as a colab.

**Comment by nihit** [comment]
thanks @turian, actually chain of thought prompting is supported for classification and entity matching tasks as well. The docs for chain of thought could definitely be improved to make this clear though! Thanks for flagging it - we will update the docs and also add an example Colab demonstrating it.

In our benchmarking experiments (https://www.refuel.ai/blog-posts/llm-labeling-technical-report), we did find that CoT primarily seems to help with question answering tasks. But, would love to hear how it performs for some of the classification/entity match experiments you might have in mind!

**Comment by turian** [comment]
@nihit Great! Would love to try it. Let me know as the docs progress. I had a challenging classification with not such good results, but it would doing good with "explain your reasoning" in chatgpt.

**Comment by nihit** [comment]
thanks @turian, and sorry for not getting to this sooner -  we've updated the docs and added a couple of examples. Some pointers:
1. Updated documentation highlighting the changes needed for chain of thought: https://docs.refuel.ai/guide/accuracy/chain-of-thought/.
2. Updated config example for a question answering task (SQuAD) - https://github.com/refuel-ai/autolabel/blob/main/examples/squad_v2/config_squad_v2_with_cot.json
3. Update config + notebook example for a classification task (Civil Comments) - https://github.com/refuel-ai/autolabel/blob/main/examples/civil_comments/example_civil_comments.ipynb (Look for "Integrating Chain of thought prompting")
