### ISSUE TITLE
[Bug]: AttributeError: type object 'DatasetLoader' has no attribute 'read_file'

### ISSUE THREAD

**Issue by turian** [refuel-ai/autolabel#440]
**Describe the bug**

When adding chain-of-thought to a classification JSON (related #425), `agent.generate_explanations("my-seed.csv")` fails with the following:

```
File /usr/local/lib/python3.11/site-packages/autolabel/labeler.py:447, in LabelingAgent.generate_explanations(self, seed_examples)
    445 if isinstance(seed_examples, str):
    446     out_file = seed_examples
--> 447     _, seed_examples, _ = DatasetLoader.read_file(seed_examples, self.config)
    449 explanation_column = self.config.explanation_column()
    450 if not explanation_column:

AttributeError: type object 'DatasetLoader' has no attribute 'read_file'
```

**To Reproduce**

I'm running `refuel-autolabel 0.0.7` from pypi, the latest. (p.s. is there no version number anywhere in the module? I couldn't find it.)

I have a classification config, and then I added explanation_column and example_template.

Then, try to run `agent.generate_explanations("my-seed.csv")` and get the error above. `agent.run` works just fine on the original JSON without explanation fields.

**Expected behavior**

Explanations should be generated. (The docs don't indicate whether I get a `df` or whether my `.csv` is overwritten with explanations.)

**Screenshots**

**Additional context**

**Comment by nihit** [comment]
thanks for flagging this @turian! This was recently introduced by some of the config and dataset validation we added - should be fixed by https://github.com/refuel-ai/autolabel/pull/441 and will be part of the 0.0.8 release today

**Comment by nihit** [comment]
https://pypi.org/project/refuel-autolabel/0.0.8/

**Comment by nihit** [comment]
@turian also, thank you for flagging the version number. 
So far, we only used to maintain it in pyproject.toml, but with 0.0.8 this is also added to the module:

```
In [1]: import autolabel

In [2]: autolabel.__version__
Out[2]: '0.0.8'
```
