### ISSUE TITLE
Interactive workflow to create labeling configs

### ISSUE THREAD

**Issue by nihit** [refuel-ai/autolabel#456]
**Is your feature request related to a problem? Please describe.**

Each labeling run with the autolabel library requires a config to be specified. These configs contain the following top-level keys: 
1. task name
2. task type
3. dataset details
4. labeling task details
5. llm model details.

Docs: https://docs.refuel.ai/guide/resources/configs/

It can be a bit hard to construct a config for a task from scratch.

**Describe the solution you'd like**

Provide an interactive (cli) workflow to help a user construct this step by step.
1. task name
2. task type
3. llm provider + model

based on these inputs, create a template json config, with placeholder values for all required columns, and default values for all optional columns.

**Comment by rishabh-bhargava** [comment]
super excited for this!
