### ISSUE TITLE
[Feature Request]: Support for Generating synthetic seed (labeled) sets

### ISSUE THREAD

**Issue by nihit** [refuel-ai/autolabel#464]
**Is your feature request related to a problem? Please describe.**
We have seen on many occasions the importance of providing a few demonstration examples to the LLM to help improve its performance (https://docs.refuel.ai/guide/accuracy/few-shot/) compared to zero-shot labeling setups.

**Describe the solution you'd like**
For some datasets and tasks, it might be useful to get the LLM to generate this labeled set if a user doesn't have any labels. 

E.g. 
1. asking the LLM to write 5 sentences with names of cities/countries etc for a location entity recognition task:
<img width="854" alt="Screen Shot 2023-07-17 at 10 25 10 PM" src="https://github.com/refuel-ai/autolabel/assets/1181800/2ee665e3-02b0-4ea3-8f94-210bfb5318b4">

2. asking the LLM to generate positive/negative pairs for matching type tasks
<img width="721" alt="Screen Shot 2023-07-17 at 10 27 11 PM" src="https://github.com/refuel-ai/autolabel/assets/1181800/cbd69448-043c-4e43-a58f-0fd7274a5ecd">

**Comment by Tyrest** [comment]
Added documentation in #544
