### ISSUE TITLE
[Proposal]: Adding Transformations for Loading and Preprocessing Datasets

### ISSUE THREAD

**Issue by rajasbansal** [refuel-ai/autolabel#492]
Currently, Autolabel only supports using the data available in a CSV/JSON file that is explicitly provided by the user. However, we want to provide the ability to preprocess data which may be present in various forms -

- Fetching information from web searches or webpages
- Reading different document formats (PDFs, Word docs, etc) from file inputs
- Reading from cloud / DB storage

We want to provide the user to do this in Autolabel directly using a new construct called Transforms. These will be similar to a 'Map' function on a dataset. The interface for a transform would look like this -

```
class Transform(ABC):
     def __init__(self, config):
         self.config = config

    @abstractmethod
    def name(self):
         return "transform_name"

    @abstractmethod
    def transform(self, row: Dict[str, Any]) -> Dict[str, Any]:
        """The transform would take in the row with all input columns and output consists of a mapping between column names and their values. Here we just return the output columns to avoid copying data."""
```

These transformations will be defined in the config by adding a new key called transforms:
```
config = {
     'dataset': ...,
     'task_name': ...,
     'transforms' : [
           {
               'name': 'tokenize',
               'params': {...},
               'input_column': '{col1}/{col2}',
               'output_columns': ['col3', 'col4'], 
         },
        {
               'name': 'padding',
               'params': {...},
               'input_column': '',
              'output_columns': ['col5'], 
       }
   ],
  'prompt': ...
}
```

Every transform can specified by using its name. Any params needed for the transform can be passed into the params which will be passed into the transform while initializing it. The input column can be a string combination of columns sent into the transform. We allow a list of multiple output columns in keeping with the multiple output columns supported in the transform signature.

If a user wants to define their own custom transformation, they just need to implement transform interface with their own custom transformation logic. The way for autolabel to recognize a custom transformation would be through register_transformation, which registers all transformations in the local registry to use with the agent.

**Datasets**
With this change, we will expose the AutolabelDataset class to the user. Now, a user will initialize their dataset using the config. However, every agent function will now accept AutolabelDataset and return AutolabelDataset.

```
agent.plan(dataset: AutolabelDataset, ...) -> None
agent.run(dataset: AutolabelDataset, ...) -> AutolabelDataset, ...
```

In order to run a transformation, the user will need to use `agent.transform` function. I.e
```
ds = agent.transform(ds)
df = agent.run(ds)
```

**Comment by nihit** [comment]
@yadavsahil197 @rajasbansal are working on this
