### ISSUE TITLE
Why use custom implementations?

### ISSUE THREAD

**Issue by krrishdholakia** [refuel-ai/autolabel#509]
Hey @Tyrest @rajasbansal 

I was looking at the way you're calling models, and i noticed that despite importing langchain, you have custom abstraction classes on top of each provider.  

I'm curious why that is? Is that because of the token calculation work? 
https://github.com/refuel-ai/autolabel/blob/06893f8ee348a4d01c5904a8888a2c4c44a4be8a/src/autolabel/models/anthropic.py#L51C5-L51C5

For context, I'm working on my own [model I/O library](https://github.com/BerriAI/litellm).

**Comment by rajasbansal** [comment]
A few reasons -
1. Chat models and non chat models were handled differently by langchain and our usecase required a single class to handle both with the ability to just change the model
2. We wanted to add additional functions like get_cost etc specific to our usecase
3. All langchain models have different parameters for things like max_tokens, temperature and these have different names. We want to unify these parameters in our abstraction

litellm looks interesting! We would be open to switching if we get the same functionality. Feel free to open a PR for what a change would look like

**Comment by DhruvaBansal00** [comment]
@krrishdholakia great to see you here. Happy to chat more once you have the PR ready :)

**Comment by krrishdholakia** [comment]
Sounds great Dhruva 😁
