### ISSUE TITLE
[Bug]: Autolabel caching leads to fewer labels being computed than expected

### ISSUE THREAD

**Issue by DhruvaBansal00** [refuel-ai/autolabel#581]
**Describe the bug**
Only 100 labels are computed even though max_items is set to 1000 while running agent.run(..)

**To Reproduce**
1. Run agent.run() with max_items set to 100 for any task. Let the run complete and for metrics to show up.
2. Without deleting the cache, change max_items to 1000. The progress bar shows only 100 elements and finishes after computing 100 labels (presumably fetching them from the cache).

**Expected behavior**
All 1000 labels should be computed

**Screenshots**
<img width="1077" alt="Screenshot 2023-09-19 at 6 00 31 PM" src="https://github.com/refuel-ai/autolabel/assets/26373935/f24b4278-6895-467a-a311-7e50a57f5516">

**Comment by mkchaitanya03** [comment]
Hi Dhruva,
Since we are assigning the result of agent.run() to ds, the next time we run with max_items > previous max_items it considers previous max_items. We could instead do :
ds_labeled = agent.run(ds, max_items=100)

**Comment by DhruvaBansal00** [comment]
Oh actually that makes a lot of sense. Thanks!
