### ISSUE TITLE
LLM response is empty

### ISSUE THREAD

**Issue by lifuyangll** [refuel-ai/autolabel#657]
autolabel.tasks.base WARNING: LLM response is empty

**Comment by rajasbansal** [comment]
Hey could you give more context on the task here? Looks like the LLM response for the prompt might be empty here.

**Comment by lifuyangll** [comment]
![image](https://github.com/refuel-ai/autolabel/assets/71159929/9a5d4564-526d-44f1-836f-790011e171ef
![111](https://github.com/refuel-ai/autolabel/assets/71159929/1cbee36d-68ff-42c7-bca7-8ffb405c760b)
Is it because the chatglm model is not supported?

**Comment by lifuyangll** [comment]
> Hey could you give more context on the task here? Looks like the LLM response for the prompt might be empty here.
![111](https://github.com/refuel-ai/autolabel/assets/71159929/301e9d71-6a69-47ae-bc57-02522ff62d87)
Is it because the chatglm model is not supported?
